Repository mozilla-mobile/reference-browser, pull requests merged in 2018-12, with the labels that each got.

#321 Issue #223: Integrating feature prompts component.
  app/build.gradle
  app/src/main/java/org/mozilla/reference/browser/browser/BrowserFragment.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: 🕵️‍♀️ needs review

#351 Closes #331: Enter/exit immersive mode as fullscreen changes
  app/src/main/java/org/mozilla/reference/browser/browser/BrowserFragment.kt
  app/src/main/res/layout/fragment_browser.xml
Labels: :stop_sign: blocked

#364 Closes #342: Update Desktop Mode checkbox
  app/src/main/java/org/mozilla/reference/browser/components/Toolbar.kt
Labels: 🕵️‍♀️ needs review

#356 Allow specifying application-services dependency substitution via local.properties
  README.md
  app/build.gradle
  app/src/main/java/org/mozilla/reference/browser/BrowserApplication.kt
  settings.gradle
Labels: 🏗️ build
