Repository mozilla-mobile/reference-browser, pull requests merged in 2019-03, with the labels that each got.

#633 Automated testing: SetUp for TabTrayMenu tests
  app/src/androidTest/java/org/mozilla/reference/browser/ui/TabTrayMenuTest.kt
  app/src/androidTest/java/org/mozilla/reference/browser/ui/robots/TabTrayMenuRobot.kt
Labels: ✅ testing

#641 Bug 1533393 - Add jobs on push and report results on Treeherder
  .taskcluster.yml
  automation/taskcluster/decision_task.py
Labels: in progress

#630 UI tests: add new/update tests for three dot (main) menu
  app/build.gradle
  app/src/androidTest/assets/pages/generic1.html
  app/src/androidTest/assets/pages/generic2.html
  app/src/androidTest/assets/pages/generic3.html
  app/src/androidTest/assets/pages/jquery-1.10.2.js
  app/src/androidTest/assets/pages/lorem-ipsum.html
  app/src/androidTest/assets/pages/refresh.html
  app/src/androidTest/java/org/mozilla/reference/browser/helpers/BrowserActivityTestRule.kt
  app/src/androidTest/java/org/mozilla/reference/browser/helpers/MockWebServer.kt
  app/src/androidTest/java/org/mozilla/reference/browser/helpers/SessionLoadedIdlingResource.kt
  app/src/androidTest/java/org/mozilla/reference/browser/helpers/TestAssetHelper.kt
  app/src/androidTest/java/org/mozilla/reference/browser/ui/FirstRunTest.kt
  app/src/androidTest/java/org/mozilla/reference/browser/ui/SettingsViewTest.kt
  app/src/androidTest/java/org/mozilla/reference/browser/ui/TabTrayMenuTest.kt
  app/src/androidTest/java/org/mozilla/reference/browser/ui/ThreeDotMenuTest.kt
  app/src/androidTest/java/org/mozilla/reference/browser/ui/robots/AwesomeBarRobot.kt
  app/src/androidTest/java/org/mozilla/reference/browser/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/reference/browser/ui/robots/ContentPanelRobot.kt
  app/src/androidTest/java/org/mozilla/reference/browser/ui/robots/FindInPagePanelRobot.kt
  app/src/androidTest/java/org/mozilla/reference/browser/ui/robots/NavigationToolbarRobot.kt
  app/src/androidTest/java/org/mozilla/reference/browser/ui/robots/ThreeDotMenuRobot.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: ✅ testing

#650 Upgrade AC dependency to 0.47.0-SNAPSHOT and GV to 67.0.20190312095443.
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Gecko.kt
Labels: 🕵️‍♀️ needs review

#651 Expose build artifacts
  automation/taskcluster/decision_task.py
  automation/taskcluster/lib/tasks.py
Labels: 🤖 automation
