Repository mozilla-mobile/reference-browser, pull requests merged in 2025-09, with the labels that each got.

#3813 Update DAGP to version 3.0.1
  gradle/libs.versions.toml
Labels: needs landing

#3821 Enable non-transitive R classes
  app/src/androidTest/java/org/mozilla/reference/browser/ui/TabTrayMenuTest.kt
  app/src/androidTest/java/org/mozilla/reference/browser/ui/robots/AddonsManagerRobot.kt
  app/src/androidTest/java/org/mozilla/reference/browser/ui/robots/AwesomeBarRobot.kt
  app/src/androidTest/java/org/mozilla/reference/browser/ui/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/reference/browser/ui/robots/CustomTabRobot.kt
  app/src/androidTest/java/org/mozilla/reference/browser/ui/robots/FindInPagePanelRobot.kt
  app/src/androidTest/java/org/mozilla/reference/browser/ui/robots/NavigationToolbarRobot.kt
  app/src/androidTest/java/org/mozilla/reference/browser/ui/robots/ReaderViewRobot.kt
  app/src/androidTest/java/org/mozilla/reference/browser/ui/robots/SettingsViewRobot.kt
  app/src/androidTest/java/org/mozilla/reference/browser/ui/robots/ThreeDotMenuRobot.kt
  app/src/main/java/org/mozilla/reference/browser/addons/AddonDetailsActivity.kt
  app/src/main/java/org/mozilla/reference/browser/addons/AddonsFragment.kt
  app/src/main/java/org/mozilla/reference/browser/addons/InstalledAddonDetailsActivity.kt
  app/src/main/java/org/mozilla/reference/browser/addons/WebExtensionPromptFeature.kt
  app/src/main/java/org/mozilla/reference/browser/browser/ReaderViewIntegration.kt
  app/src/main/java/org/mozilla/reference/browser/tabs/TabsPanel.kt
  app/src/main/java/org/mozilla/reference/browser/tabs/TabsToolbar.kt
  gradle.properties
Labels: needs landing

#3824 Close #3623 - Fix back handling for browser navigation
  app/src/main/java/org/mozilla/reference/browser/BrowserActivity.kt
Labels: needs landing

#3826 Issue #3623 - Don't call super.onBackPressedDispatcher
  app/src/main/java/org/mozilla/reference/browser/BrowserActivity.kt
Labels: needs landing

#3842 Update Kotlin to version 2.2.20
  gradle/libs.versions.toml
Labels: needs landing

#3843 Pick up the 2025-09-10 AndroidX library updates
  gradle/libs.versions.toml
Labels: needs landing

#3853 Update DAGP to version 3.0.3
  gradle/libs.versions.toml
Labels: needs landing

#3864 Fix the Nightly build task link on Readme.
  README.md
Labels: needs landing

#3876 Update JNA to version 5.18.0
  gradle/libs.versions.toml
Labels: needs landing, queued

#3875 Update Android Components version
  gradle/libs.versions.toml
Labels: queued

#3883 Update Android Components version
  gradle/libs.versions.toml
Labels: queued

#3878 Fix toolbar colours
  app/src/main/java/org/mozilla/reference/browser/browser/ToolbarIntegration.kt
Labels: needs landing, queued

#3873 Remove Raptor variant and build transforms
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/reference/browser/BrowserTestActivity.kt
  taskcluster/config.yml
  taskcluster/kinds/build/kind.yml
  taskcluster/kinds/raptor/kind.yml
  taskcluster/kinds/signing/kind.yml
  taskcluster/kinds/test/kind.yml
  taskcluster/rb_taskgraph/gradle.py
  taskcluster/rb_taskgraph/transforms/raptor.py
Labels: needs landing, queued

#3886 Update Android Components version
  gradle/libs.versions.toml
Labels: queued

#3887 Update Android Components version
  gradle/libs.versions.toml
Labels: queued

#3888 Fix incorrect reference to menuController in toolbar
  app/src/main/java/org/mozilla/reference/browser/browser/ToolbarIntegration.kt
Labels: needs landing, queued

#3890 Update Android Components version
  gradle/libs.versions.toml
Labels: queued

#3891 Update Android Components version
  gradle/libs.versions.toml
Labels: queued

#3892 Update Android Components version
  gradle/libs.versions.toml
Labels: queued

#3895 Update Android Components version
  gradle/libs.versions.toml
Labels: queued

#3897 Update Nexus to version 2.15.2-03
  taskcluster/docker/android-build/Dockerfile
Labels: needs landing
